typography_spectrum: 0.6459500987548381
content_rating:
  adult: false
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.39226992172189057
  lightness: 0.5838704751804471
  saturation: 0.14527779584750533
  rhythmicContrast: 0.2646464242134243
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.6657695756293833
author:
  name: ''
  url: ''
  email: ''
name: Harmless Stories
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/Danger.Juggling.Show/'
    type: external
  - name: Twitter
    url: 'https://twitter.com/LiamFateSelvey'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/liamfateselvey/'
    type: external
  - name: Hire Me!
    url: dangerjugglingshow.com
    type: external
title: A Tribute to Navel-gazing
description: Upping the ante
